"""create catalog_models table

Revision ID: 091025c3169a
Revises: 716bfe422069
Create Date: 2026-09-14 01:25:41.800993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091025c3169a'
down_revision: Union[str, None] = '716bfe422069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('dossier_image', sa.String(length=500), nullable=False),
    sa.Column('pose_count', sa.Integer(), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('undertone', sa.String(length=20), nullable=False),
    sa.Column('height', sa.String(length=50), nullable=False),
    sa.Column('body_shape', sa.String(length=100), nullable=False),
    sa.Column('waist', sa.String(length=50), nullable=False),
    sa.Column('personal_color', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_models')
    # ### end Alembic commands ###
