"""add axis to quiz questions and options

Revision ID: 23c375f82230
Revises: a65d946bca40
Create Date: 2026-09-16 02:23:13.181057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c375f82230'
down_revision: Union[str, None] = 'a65d946bca40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_options', sa.Column('axis_value', sa.String(length=20), nullable=False))
    op.drop_column('quiz_options', 'season')
    op.add_column('quiz_questions', sa.Column('axis', sa.String(length=20), nullable=False))
    op.add_column('quiz_questions', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'image_url')
    op.drop_column('quiz_questions', 'axis')
    op.add_column('quiz_options', sa.Column('season', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('quiz_options', 'axis_value')
    # ### end Alembic commands ###
