"""create accessory_products table

Revision ID: 3f56461f19fc
Revises: ca6c42dc2217
Create Date: 2026-09-17 10:43:27.330764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f56461f19fc'
down_revision: Union[str, None] = 'ca6c42dc2217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('affiliate_link', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('style_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occasion_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tone_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Note: autogenerate also proposed `alter_column(..., nullable=False)`
    # on several quiz_attempts columns here — that's pre-existing,
    # unrelated drift (those columns are deliberately nullable in the DB
    # to accommodate legacy pre-quiz-v2 rows, per
    # 2026-09-16-personal-color-quiz-v2-design.md) and was removed from
    # this migration, which only creates accessory_products.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accessory_products')
    # ### end Alembic commands ###
