"""add side_image to catalog_models

Revision ID: 4c71ffddd370
Revises: 005a8816383c
Create Date: 2026-09-15 05:04:48.308803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c71ffddd370'
down_revision: Union[str, None] = '005a8816383c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_models', sa.Column('side_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_models', 'side_image')
    # ### end Alembic commands ###
