"""create faq_items table

Revision ID: 64876ac85c5d
Revises: 99a27e48d2e3
Create Date: 2026-09-13 21:13:11.041489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64876ac85c5d'
down_revision: Union[str, None] = '99a27e48d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_markdown', sa.Text(), nullable=False),
    sa.Column('highlight_icon', sa.String(length=50), nullable=True),
    sa.Column('highlight_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq_items')
    # ### end Alembic commands ###
