"""add scoring fields to quiz attempts

Revision ID: 6a7ec4bb7ba4
Revises: 23c375f82230
Create Date: 2026-09-16 02:25:35.631644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7ec4bb7ba4'
down_revision: Union[str, None] = '23c375f82230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable at the DB level (unlike the SQLAlchemy model, which types these
    # as non-nullable for the app's own writes) so existing rows from the old
    # single-`season` schema don't violate a NOT NULL constraint — they aren't
    # backfilled with a reconstructed sub-season, per the design spec.
    op.add_column('quiz_attempts', sa.Column('sub_season', sa.String(length=30), nullable=True))
    op.add_column('quiz_attempts', sa.Column('parent_season', sa.String(length=20), nullable=True))
    op.add_column('quiz_attempts', sa.Column('hue_result', sa.String(length=20), nullable=True))
    op.add_column('quiz_attempts', sa.Column('value_result', sa.String(length=20), nullable=True))
    op.add_column('quiz_attempts', sa.Column('chroma_result', sa.String(length=20), nullable=True))
    op.drop_column('quiz_attempts', 'season')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('season', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('quiz_attempts', 'chroma_result')
    op.drop_column('quiz_attempts', 'value_result')
    op.drop_column('quiz_attempts', 'hue_result')
    op.drop_column('quiz_attempts', 'parent_season')
    op.drop_column('quiz_attempts', 'sub_season')
    # ### end Alembic commands ###
