"""add forum image, comments, and likes

Revision ID: 77a65c326cf3
Revises: 6a7ec4bb7ba4
Create Date: 2026-09-16 03:42:47.285030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a65c326cf3'
down_revision: Union[str, None] = '6a7ec4bb7ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_comments_post_id'), 'forum_comments', ['post_id'], unique=False)
    op.create_table('forum_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_forum_likes_post_user')
    )
    op.create_index(op.f('ix_forum_likes_post_id'), 'forum_likes', ['post_id'], unique=False)
    op.add_column('forum_posts', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # Note: autogenerate also proposed NOT NULL alter_column statements on
    # quiz_attempts.{sub_season,parent_season,hue_result,value_result,chroma_result}.
    # Those are pre-existing, deliberate drift (see the quiz-attempts scoring
    # migration) — the DB columns are intentionally nullable to tolerate
    # historical rows, even though the ORM model types them as non-nullable
    # for the app's own writes. Unrelated to this forum change; omitted.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_posts', 'image_url')
    op.drop_index(op.f('ix_forum_likes_post_id'), table_name='forum_likes')
    op.drop_table('forum_likes')
    op.drop_index(op.f('ix_forum_comments_post_id'), table_name='forum_comments')
    op.drop_table('forum_comments')
    # ### end Alembic commands ###
