"""add pose to tryon_jobs

Revision ID: be5426f70de0
Revises: 4c71ffddd370
Create Date: 2026-09-15 05:06:56.383966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5426f70de0'
down_revision: Union[str, None] = '4c71ffddd370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tryon_jobs', sa.Column('pose', sa.String(length=20), nullable=False, server_default='front'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tryon_jobs', 'pose')
    # ### end Alembic commands ###
