"""add forum bookmarks

Revision ID: ca6c42dc2217
Revises: 77a65c326cf3
Create Date: 2026-09-16 04:24:06.706610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6c42dc2217'
down_revision: Union[str, None] = '77a65c326cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_forum_bookmarks_post_user')
    )
    op.create_index(op.f('ix_forum_bookmarks_post_id'), 'forum_bookmarks', ['post_id'], unique=False)
    op.create_index(op.f('ix_forum_bookmarks_user_id'), 'forum_bookmarks', ['user_id'], unique=False)
    # Note: autogenerate also proposed NOT NULL alter_column statements on
    # quiz_attempts.{sub_season,parent_season,hue_result,value_result,chroma_result}.
    # Those are pre-existing, deliberate drift (see the quiz-attempts scoring
    # migration and the comment in 77a65c326cf3) — the DB columns are
    # intentionally nullable to tolerate historical rows, even though the ORM
    # model types them as non-nullable for the app's own writes. Unrelated to
    # this forum change; omitted.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_bookmarks_user_id'), table_name='forum_bookmarks')
    op.drop_index(op.f('ix_forum_bookmarks_post_id'), table_name='forum_bookmarks')
    op.drop_table('forum_bookmarks')
    # ### end Alembic commands ###
